-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") FROM MEMBER_PROFILE
    where DATE_FORMAT(DATE_OF_BIRTH, "%m") = '03' AND GENDER = 'W' AND TLNO IS NOT Null
    ORDER BY MEMBER_ID ASC
