-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, 
    MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID FROM ECOLI_DATA AS E
JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MAX_SIZE_PER_YEAR ON MAX_SIZE_PER_YEAR.YEAR = YEAR(E.DIFFERENTIATION_DATE)

ORDER BY YEAR, YEAR_DEV